// Datos sacados de la wiki de Valheim (Fandom) en septiembre de 2026, juego en 1.0.
// Los nombres de Ashlands son traducción propia; el nombre en inglés va de subtítulo
// para poder encontrarlos en el juego.

// Biomas que se pueden elegir. "granja" = lo que se cría o cultiva en la base.
window.BIOMES = [
  { id: "praderas",  name: "Praderas",     img: "b-meadows" },
  { id: "bosque",    name: "Bosque Negro", img: "b-blackforest" },
  { id: "pantano",   name: "Pantano",      img: "b-swamp" },
  { id: "montana",   name: "Montaña",      img: "b-mountain" },
  { id: "llanuras",  name: "Llanuras",     img: "b-plains" },
  { id: "oceano",    name: "Océano",       img: "b-ocean" },
  { id: "mistlands", name: "Mistlands",    img: "b-mistlands" },
  { id: "ashlands",  name: "Ashlands",     img: "b-ashlands" },
  { id: "granja",    name: "Granja en casa", img: "colmena", note: "Miel, huevos y huerto" },
];
window.DEFAULT_BIOMES = ["praderas", "bosque", "llanuras", "ashlands", "granja"];

window.SOURCES = {
  "b-meadows":     { name: "Praderas",       kind: "Bioma" },
  "b-blackforest": { name: "Bosque Negro",   kind: "Bioma" },
  "b-swamp":       { name: "Pantano",        kind: "Bioma" },
  "b-mountain":    { name: "Montaña",        kind: "Bioma" },
  "b-plains":      { name: "Llanuras",       kind: "Bioma" },
  "b-ocean":       { name: "Océano",         kind: "Bioma" },
  "b-mistlands":   { name: "Mistlands",      kind: "Bioma" },
  "b-ashlands":    { name: "Ashlands",       kind: "Bioma" },
  "asksvin":     { name: "Asksvin",      kind: "Criatura · Ashlands" },
  "volture":     { name: "Volture",      kind: "Criatura · Ashlands" },
  "bonemaw":     { name: "Bonemaw",      kind: "Criatura · mar de Ashlands" },
  "liebre":      { name: "Liebre",       kind: "Criatura · Mistlands" },
  "seeker":      { name: "Seeker",       kind: "Criatura · Mistlands" },
  "lox":         { name: "Lox",          kind: "Criatura · Llanuras" },
  "lobo":        { name: "Lobo",         kind: "Criatura · Montaña" },
  "drake":       { name: "Drake",        kind: "Criatura · Montaña" },
  "sanguijuela": { name: "Sanguijuela",  kind: "Criatura · Pantano" },
  "greydwarf":   { name: "Greydwarf",    kind: "Criatura · Praderas y Bosque Negro" },
  "serpiente":   { name: "Serpiente",    kind: "Criatura · Océano" },
  "garrapata":   { name: "Garrapata",    kind: "Criatura · Mistlands" },
  "cria-seeker": { name: "Cría de Seeker", kind: "Criatura · minas infestadas" },
  "extractor":   { name: "Extractor de savia", kind: "Mistlands" },
  "gallina":     { name: "Gallina",      kind: "Granja" },
  "cultivador":  { name: "Cultivador",          kind: "Plantar en la base" },
  "colmena":     { name: "Colmena",             kind: "Base" },
  "molino":      { name: "Molino de viento",    kind: "Base" },
  "mesa-prep":   { name: "Mesa de preparación", kind: "Base" },
  "cana":        { name: "Caña de pescar",      kind: "Pesca" },
  "bruja":        { name: "Bruja del Pantano",   kind: "Comercio · después de Moder" },
  "neck":         { name: "Neck",                kind: "Criatura · Praderas" },
  "horno-carbon": { name: "Horno de carbón",     kind: "Base" },
};

// biomes: basta con ir a UNO de ellos para conseguirlo
window.INGREDIENTS = [
  // Ashlands
  { id: "vinebaya", name: "Racimo de vinebaya", en: "Vineberry cluster", biomes: ["ashlands"],
    sources: [
      { id: "b-ashlands", how: "Crece en las enredaderas de las ruinas carbonizadas." },
      { id: "cultivador", how: "Con las primeras semillas se planta en cualquier bioma, pegada a una pared plana para trepar. Crece muy rápido." },
    ] },
  { id: "cola-asksvin", name: "Cola de Asksvin", en: "Asksvin tail", biomes: ["ashlands"],
    sources: [ { id: "asksvin", how: "La sueltan los Asksvin adultos y las crías. Cazarlos también da cuero para el Slayer." } ] },
  { id: "carne-volture", name: "Carne de Volture", en: "Volture meat", biomes: ["ashlands"],
    sources: [ { id: "volture", how: "La sueltan los Volture, los buitres de los nidos y de la costa." } ] },
  { id: "huevo-volture", name: "Huevo de Volture", en: "Volture egg", biomes: ["ashlands"],
    sources: [ { id: "volture", how: "Lo sueltan los Volture." } ] },
  { id: "fiddlehead", name: "Fiddlehead", en: "Fiddlehead", biomes: ["ashlands"],
    sources: [ { id: "b-ashlands", how: "Se junta del suelo en Ashlands. No hay dato de que se pueda plantar." } ] },
  { id: "smokepuff", name: "Smoke puff", en: "Smoke puff", biomes: ["ashlands"],
    sources: [ { id: "b-ashlands", how: "Se encuentra en el suelo de Ashlands." } ] },
  { id: "carne-bonemaw", name: "Carne de Bonemaw", en: "Bonemaw meat", biomes: ["ashlands"],
    sources: [ { id: "bonemaw", how: "La suelta el Bonemaw, la serpiente de hueso del mar de Ashlands. Se cocina en la estación de hierro." } ] },
  // Mistlands
  { id: "jotun", name: "Jotun puffs", en: "Jotun puffs", biomes: ["mistlands"],
    sources: [
      { id: "b-mistlands", how: "Los hongos amarillos del suelo de Mistlands." },
      { id: "cultivador", how: "Se plantan, pero solo crecen en Mistlands." },
    ] },
  { id: "carne-liebre", name: "Carne de liebre", en: "Hare meat", biomes: ["mistlands"],
    sources: [ { id: "liebre", how: "De las liebres de Mistlands." } ] },
  { id: "carne-seeker", name: "Carne de Seeker", en: "Seeker meat", biomes: ["mistlands"],
    sources: [ { id: "seeker", how: "La sueltan los Seeker y los Seeker Soldier." } ] },
  { id: "pez-linterna", name: "Pez linterna", en: "Anglerfish", biomes: ["mistlands"],
    sources: [ { id: "cana", how: "Se pesca en la costa de Mistlands con carnada de niebla, que se hace en la mesa de preparación." } ] },
  { id: "magecap", name: "Magecap", en: "Magecap", biomes: ["mistlands"],
    sources: [
      { id: "b-mistlands", how: "Hongo azul brillante del suelo de Mistlands." },
      { id: "cultivador", how: "Se planta, pero solo crece en Mistlands." },
    ] },
  { id: "savia", name: "Savia", en: "Sap", biomes: ["mistlands"],
    sources: [ { id: "extractor", how: "Extractor de savia puesto sobre las raíces ancestrales de Mistlands. Solo junta mientras hay alguien cerca, así que conviene llenar cofres en un viaje." } ] },
  { id: "jalea", name: "Jalea real", en: "Royal jelly", biomes: ["mistlands"],
    sources: [ { id: "cria-seeker", how: "La sueltan las crías de Seeker y está en montones dentro de las minas infestadas." } ] },
  { id: "coagulo", name: "Coágulo de sangre", en: "Blood clot", biomes: ["mistlands"],
    sources: [ { id: "garrapata", how: "Lo sueltan las garrapatas de Mistlands." } ] },
  // Llanuras
  { id: "cebada", name: "Cebada", en: "Barley", biomes: ["llanuras"],
    sources: [ { id: "b-plains", how: "Cebada entera, sin moler. Solo crece en las Llanuras." } ] },
  { id: "harina", name: "Harina de cebada", en: "Barley flour", biomes: ["llanuras"],
    sources: [
      { id: "b-plains", how: "La cebada solo crece en las Llanuras: sembrala allá con el cultivador." },
      { id: "molino", how: "La cebada va al molino de viento y sale harina." },
    ] },
  { id: "masa-pan", name: "Masa de pan", en: "Bread dough", biomes: ["llanuras"],
    sources: [ { id: "mesa-prep", how: "Se amasa en la mesa de preparación con harina de cebada." } ] },
  { id: "moras-nubes", name: "Moras nubes", en: "Cloudberries", biomes: ["llanuras"],
    sources: [ { id: "b-plains", how: "Arbustos bajos de las Llanuras." } ] },
  { id: "carne-lox", name: "Carne de Lox", en: "Lox meat", biomes: ["llanuras"],
    sources: [ { id: "lox", how: "De los Lox. Si tienen Lox domesticados, se crían en el corral." } ] },
  // biomas viejos
  { id: "hongo", name: "Hongo", en: "Mushroom", biomes: ["praderas", "bosque", "pantano"],
    sources: [ { id: "b-meadows", how: "Del suelo en Praderas, Bosque Negro y Pantano. Reaparecen solos." } ] },
  { id: "ojo-greydwarf", name: "Ojo de Greydwarf", en: "Greydwarf eye", biomes: ["praderas", "bosque"],
    sources: [ { id: "greydwarf", how: "Lo sueltan los Greydwarf. Un nido cerca de la base los da sin parar." } ] },
  { id: "cardo", name: "Cardo", en: "Thistle", biomes: ["bosque", "pantano"],
    sources: [ { id: "b-blackforest", how: "Flor azul que brilla de noche, en Bosque Negro y Pantano." } ] },
  { id: "bolsa-sangre", name: "Bolsa de sangre", en: "Bloodbag", biomes: ["pantano"],
    sources: [ { id: "sanguijuela", how: "La sueltan las sanguijuelas del agua del Pantano." } ] },
  { id: "carne-lobo", name: "Carne de lobo", en: "Wolf meat", biomes: ["montana"],
    sources: [ { id: "lobo", how: "De los lobos de la Montaña. Si los domesticaron, se crían." } ] },
  { id: "glandula", name: "Glándula helada", en: "Freeze gland", biomes: ["montana"],
    sources: [ { id: "drake", how: "La sueltan los Drake de la Montaña." } ] },
  { id: "carne-serpiente", name: "Carne de serpiente", en: "Serpent meat", biomes: ["oceano"],
    sources: [ { id: "serpiente", how: "De las serpientes marinas, en mar abierto y con tormenta. Se cocina en la estación de hierro." } ] },
  { id: "pescado", name: "Pescado cocido", en: "Cooked fish", biomes: ["praderas", "bosque", "pantano", "llanuras", "oceano"],
    sources: [ { id: "cana", how: "Cualquier pez de ríos, lagos o mar, cocinado en la estación de cocina." } ] },
  // granja en casa
  { id: "miel", name: "Miel", en: "Honey", biomes: ["granja"],
    sources: [ { id: "colmena", how: "Varias colmenas en la base, sin techo encima." } ] },
  { id: "cebolla", name: "Cebolla", en: "Onion", biomes: ["granja"],
    sources: [ { id: "cultivador", how: "Las semillas salen de chozas de la Montaña. Después se cultivan en cualquier huerto." } ] },
  { id: "zanahoria", name: "Zanahoria", en: "Carrot", biomes: ["granja"],
    sources: [ { id: "cultivador", how: "Semillas del Bosque Negro. Se cultivan en cualquier huerto." } ] },
  { id: "huevo", name: "Huevo", en: "Egg", biomes: ["granja"],
    sources: [ { id: "gallina", how: "Las gallinas ponen huevos. El primero se le compra a Haldor." } ] },
  { id: "nabo", name: "Nabo", en: "Turnip", biomes: ["granja"],
    sources: [ { id: "cultivador", how: "Semillas de las flores amarillas del Pantano. Después se cultiva en cualquier huerto." } ] },
  { id: "carne-pollo", name: "Carne de pollo", en: "Chicken meat", biomes: ["granja"],
    sources: [ { id: "gallina", how: "Del gallinero. Se cocina en la estación de cocina." } ] },
];

// type: "salud", "vigor" o "mana" según qué da más. e = eitr (maná).
window.FOODS = [
  // salud
  { id: "pastel-picante",  name: "Pastel picante",          en: "Piquant pie",          type: "salud", h: 105, s: 35, tier: "Ashlands",  station: "Horno de piedra",
    ing: [["vinebaya", 2], ["cola-asksvin", 2], ["harina", 4]] },
  { id: "carne-machacada", name: "Carne machacada",         en: "Mashed meat",          type: "salud", h: 100, s: 34, tier: "Ashlands",  station: "Caldero",
    ing: [["cola-asksvin", 1], ["carne-volture", 1], ["fiddlehead", 1]] },
  { id: "svinstew",        name: "Guiso de cerdo ardiente", en: "Fiery svinstew",       type: "salud", h: 95,  s: 32, tier: "Ashlands",  station: "Caldero",
    ing: [["cola-asksvin", 1], ["vinebaya", 2], ["smokepuff", 1]] },
  { id: "bonemaw-asado",   name: "Carne de Bonemaw asada",  en: "Cooked bonemaw meat",  type: "salud", h: 90,  s: 30, tier: "Ashlands",  station: "Estación de cocina de hierro",
    ing: [["carne-bonemaw", 1]] },
  { id: "misthare",        name: "Misthare supreme",        en: "Misthare supreme",     type: "salud", h: 85,  s: 28, tier: "Mistlands", station: "Horno de piedra",
    ing: [["carne-liebre", 1], ["jotun", 3], ["zanahoria", 2]] },
  { id: "pollo",           name: "Pollo glaseado con miel", en: "Honey glazed chicken", type: "salud", h: 80,  s: 26, tier: "Mistlands", station: "Horno de piedra",
    ing: [["carne-pollo", 1], ["miel", 3], ["jotun", 2]] },
  { id: "bandeja",         name: "Bandeja de carne",        en: "Meat platter",         type: "salud", h: 80,  s: 26, tier: "Mistlands", station: "Horno de piedra",
    ing: [["carne-seeker", 1], ["carne-lox", 1], ["carne-liebre", 1]] },
  { id: "guiso-serpiente", name: "Guiso de serpiente",      en: "Serpent stew",         type: "salud", h: 80,  s: 26, tier: "Océano",    station: "Caldero",
    ing: [["carne-serpiente", 1], ["hongo", 1], ["miel", 2]] },
  { id: "pastel-lox",      name: "Pastel de carne de Lox",  en: "Lox meat pie",         type: "salud", h: 75,  s: 24, tier: "Llanuras",  station: "Horno de piedra",
    ing: [["carne-lox", 2], ["moras-nubes", 2], ["harina", 4]] },
  { id: "wraps",           name: "Wraps de pescado",        en: "Fish wraps",           type: "salud", h: 70,  s: 23, tier: "Llanuras",  station: "Caldero",
    ing: [["pescado", 2], ["harina", 4]] },
  { id: "cola-asada",      name: "Cola de Asksvin asada",   en: "Cooked asksvin tail",  type: "salud", h: 70,  s: 24, tier: "Ashlands",  station: "Estación de cocina de hierro",
    ing: [["cola-asksvin", 1]] },
  { id: "volture-asado",   name: "Carne de Volture asada",  en: "Cooked volture meat",  type: "salud", h: 70,  s: 24, tier: "Ashlands",  station: "Estación de cocina de hierro",
    ing: [["carne-volture", 1]] },
  { id: "brocheta-lobo",   name: "Brocheta de lobo",        en: "Wolf skewer",          type: "salud", h: 65,  s: 21, tier: "Montaña",   station: "Caldero",
    ing: [["carne-lobo", 1], ["hongo", 2], ["cebolla", 1]] },
  // vigor
  { id: "pastel-corteza",  name: "Pastel de corteza asada", en: "Roasted crust pie",    type: "vigor", h: 34,  s: 100, tier: "Ashlands",  station: "Horno de piedra",
    ing: [["vinebaya", 2], ["huevo-volture", 1], ["harina", 4]] },
  { id: "popurri",         name: "Popurrí abrasador",       en: "Scorching medley",     type: "vigor", h: 32,  s: 95,  tier: "Ashlands",  station: "Caldero",
    ing: [["jotun", 3], ["cebolla", 3], ["fiddlehead", 3]] },
  { id: "mermelada",       name: "Mermelada picante",       en: "Spicy marmalade",      type: "vigor", h: 30,  s: 90,  tier: "Ashlands",  station: "Caldero",
    ing: [["vinebaya", 3], ["miel", 1], ["fiddlehead", 1]] },
  { id: "fishnbread",      name: "Fish 'n' bread",          en: "Fish 'n' bread",       type: "vigor", h: 30,  s: 90,  tier: "Mistlands", station: "Horno de piedra",
    ing: [["pez-linterna", 1], ["masa-pan", 2]] },
  { id: "omelette",        name: "Omelette de hongos",      en: "Mushroom omelette",    type: "vigor", h: 28,  s: 85,  tier: "Mistlands", station: "Caldero",
    ing: [["huevo", 3], ["jotun", 3]] },
  { id: "ensalada",        name: "Ensalada",                en: "Salad",                type: "vigor", h: 26,  s: 80,  tier: "Mistlands", station: "Caldero",
    ing: [["jotun", 3], ["cebolla", 3], ["moras-nubes", 3]] },
  { id: "morcilla",        name: "Morcilla",                en: "Blood pudding",        type: "vigor", h: 25,  s: 75,  tier: "Llanuras",  station: "Caldero",
    ing: [["cardo", 2], ["bolsa-sangre", 2], ["harina", 4]] },
  { id: "pan",             name: "Pan",                     en: "Bread",                type: "vigor", h: 23,  s: 70,  tier: "Llanuras",  station: "Horno de piedra",
    ing: [["masa-pan", 1]] },
  { id: "eyescream",       name: "Helado de ojos",          en: "Eyescream",            type: "vigor", h: 21,  s: 65,  tier: "Montaña",   station: "Caldero",
    ing: [["ojo-greydwarf", 3], ["glandula", 1]] },
  { id: "sopa-cebolla",    name: "Sopa de cebolla",         en: "Onion soup",           type: "vigor", h: 20,  s: 60,  tier: "Montaña",   station: "Caldero",
    ing: [["cebolla", 3]] },
  // maná (eitr)
  { id: "verdes",        name: "Verduras marinadas",        en: "Marinated greens",      type: "mana", h: 32, s: 16, e: 95, tier: "Ashlands",  station: "Caldero",
    ing: [["savia", 3], ["magecap", 2], ["fiddlehead", 2], ["smokepuff", 2]] },
  { id: "shroomshake",   name: "Batido de hongos chispeante", en: "Sparkling shroomshake", type: "mana", h: 30, s: 15, e: 90, tier: "Ashlands",  station: "Caldero",
    ing: [["savia", 4], ["magecap", 2], ["vinebaya", 2], ["smokepuff", 2]] },
  { id: "aspic",         name: "Áspic de Seeker",           en: "Seeker aspic",          type: "mana", h: 28, s: 14, e: 85, tier: "Mistlands", station: "Caldero",
    ing: [["carne-seeker", 2], ["magecap", 2], ["jalea", 2]] },
  { id: "caldo-bayas",   name: "Caldo de bayas chisporroteante", en: "Sizzling berry broth", type: "mana", h: 28, s: 14, e: 85, tier: "Ashlands", station: "Caldero",
    ing: [["savia", 3], ["vinebaya", 2], ["fiddlehead", 2]] },
  { id: "porridge",      name: "Porridge de Yggdrasil",     en: "Yggdrasil porridge",    type: "mana", h: 27, s: 13, e: 80, tier: "Mistlands", station: "Caldero",
    ing: [["savia", 4], ["cebada", 3], ["jalea", 2]] },
  { id: "hongo-relleno", name: "Hongo relleno",             en: "Stuffed mushroom",      type: "mana", h: 25, s: 12, e: 75, tier: "Mistlands", station: "Horno de piedra",
    ing: [["magecap", 3], ["coagulo", 1], ["nabo", 2]] },
];

// Combinaciones: se arman solas con las comidas disponibles en los biomas elegidos.
// salud/vigor/mana = cuántas de cada tipo, tomando las mejores.
window.COMBO_RULES = [
  { id: "explorar", name: "Explorar", note: "Dos de vigor y una de salud: correr, talar y minar sin quedarte seco.", vigor: 2, salud: 1 },
  { id: "pelear",   name: "Para pelear", note: "Dos de salud y una de vigor. La balanceada.", salud: 2, vigor: 1 },
  { id: "jefes",    name: "Jefes", note: "Toda la salud posible.", salud: 3, vigor: 0 },
  { id: "juntar",   name: "Solo juntar", note: "Todo vigor, para cargar y cosechar.", salud: 0, vigor: 3 },
  { id: "mago",     name: "Mago", note: "Dos de maná y una de salud, para aguantar un golpe entre hechizo y hechizo.", mana: 2, salud: 1 },
  { id: "mago-puro", name: "Mago puro", note: "Todo maná, para tirar hechizos sin parar.", mana: 3 },
];

// IDs de juego (prefabs) para cruzar con lo que hay en los cofres de la casa (stock.js).
// Ingredientes crudos que se cocinan en el momento cuentan crudos o cocidos.
window.PIDS = {
  // ingredientes
  "vinebaya": ["Vineberry"], "cola-asksvin": ["AsksvinMeat"], "carne-volture": ["VoltureMeat"],
  "huevo-volture": ["VoltureEgg"], "fiddlehead": ["Fiddleheadfern"], "smokepuff": ["MushroomSmokePuff"],
  "carne-bonemaw": ["BoneMawSerpentMeat"], "jotun": ["MushroomJotunPuffs"], "carne-liebre": ["HareMeat"],
  "carne-seeker": ["BugMeat"], "pez-linterna": ["Fish9", "fish9"], "magecap": ["MushroomMagecap"],
  "savia": ["Sap"], "jalea": ["RoyalJelly"], "coagulo": ["GiantBloodSack"], "cebada": ["Barley"],
  "harina": ["BarleyFlour"], "masa-pan": ["BreadDough"], "moras-nubes": ["Cloudberry"],
  "carne-lox": ["LoxMeat"], "hongo": ["Mushroom"], "ojo-greydwarf": ["GreydwarfEye"], "cardo": ["Thistle"],
  "bolsa-sangre": ["Bloodbag"], "carne-lobo": ["WolfMeat"], "glandula": ["FreezeGland"],
  "carne-serpiente": ["SerpentMeat", "SerpentMeatCooked"],
  "pescado": ["FishCooked", "Fish1", "Fish2", "Fish3", "Fish4_cave", "Fish5", "Fish6", "Fish7", "Fish8", "Fish10", "Fish11", "Fish12"],
  "miel": ["Honey"], "cebolla": ["Onion"], "zanahoria": ["Carrot"], "huevo": ["ChickenEgg"], "nabo": ["Turnip"],
  "carne-pollo": ["ChickenMeat"],
  // comidas ya cocinadas
  "pastel-picante": ["PiquantPie"], "carne-machacada": ["MashedMeat"], "svinstew": ["FierySvinstew"],
  "bonemaw-asado": ["CookedBoneMawSerpentMeat"], "misthare": ["Mistharesupreme"], "pollo": ["HoneyGlazedChicken"],
  "bandeja": ["Meatplatter"], "guiso-serpiente": ["SerpentStew"], "pastel-lox": ["LoxPie"], "wraps": ["FishWraps"],
  "cola-asada": ["CookedAsksvinMeat"], "volture-asado": ["CookedVoltureMeat"], "brocheta-lobo": ["WolfMeatSkewer"],
  "pastel-corteza": ["RoastedCrustPie"], "popurri": ["ScorchingMedley"], "mermelada": ["SpicyMarmalade"],
  "fishnbread": ["FishAndBread"], "omelette": ["MushroomOmelette"], "ensalada": ["Salad"], "morcilla": ["BloodPudding"],
  "pan": ["Bread"], "eyescream": ["Eyescream"], "sopa-cebolla": ["OnionSoup"], "verdes": ["MarinatedGreens"],
  "shroomshake": ["SparklingShroomshake"], "aspic": ["SeekerAspic"], "caldo-bayas": ["SizzlingBerryBroth"],
  "porridge": ["YggdrasilPorridge"], "hongo-relleno": ["MagicallyStuffedShroom"],
};
// Lo que se puede transformar en el momento: la cebada se muele en harina.
window.CONVERTS = { "harina": { pid: "Barley", note: "cebada para moler" } };

// Comida ya cocinada que puede haber en los cofres. ref = misma entrada que en FOODS.
window.COOKED = [
  { id: "c-necktail", name: "Cola de neck asada", en: "Grilled neck tail", h: 25, s: 8, e: 0, pids: ["NeckTailGrilled"] },
  { id: "c-jabali", name: "Carne de jabalí asada", en: "Cooked boar meat", h: 30, s: 10, e: 0, pids: ["CookedMeat"] },
  { id: "c-ciervo", name: "Carne de ciervo asada", en: "Cooked deer meat", h: 35, s: 12, e: 0, pids: ["CookedDeerMeat"] },
  { id: "c-cecina-jabali", name: "Cecina de jabalí", en: "Boar jerky", h: 23, s: 23, e: 0, pids: ["BoarJerky"] },
  { id: "c-oso", name: "Carne de oso asada", en: "Cooked bear meat", h: 40, s: 13, e: 0, pids: ["CookedBjornMeat"] },
  { id: "c-salsa", name: "Salsa de carne picada", en: "Minced meat sauce", h: 40, s: 13, e: 0, pids: ["MinceMeatSauce"] },
  { id: "c-queensjam", name: "Mermelada de la reina", en: "Queen's jam", h: 14, s: 40, e: 0, pids: ["QueensJam"] },
  { id: "c-sopa-zanahoria", name: "Sopa de zanahoria", en: "Carrot soup", h: 15, s: 45, e: 0, pids: ["CarrotSoup"] },
  { id: "c-guiso-ciervo", name: "Guiso de ciervo", en: "Deer stew", h: 45, s: 15, e: 0, pids: ["DeerStew"] },
  { id: "pescado", name: "Pescado cocido", en: "Cooked fish", h: 45, s: 15, e: 0, pids: ["FishCooked"] },
  { id: "c-muckshake", name: "Batido de lodo", en: "Muckshake", h: 16, s: 50, e: 0, pids: ["ShocklateSmoothie"] },
  { id: "c-guiso-nabo", name: "Guiso de nabo", en: "Turnip stew", h: 18, s: 55, e: 0, pids: ["TurnipStew"] },
  { id: "c-salchichas", name: "Salchichas", en: "Sausages", h: 55, s: 18, e: 0, pids: ["Sausages"] },
  { id: "c-sopa-negra", name: "Sopa negra", en: "Black soup", h: 50, s: 17, e: 0, pids: ["BlackSoup"] },
  { id: "c-feast-praderas", name: "Jabalí asado entero", en: "Whole roasted Meadow boar", h: 35, s: 35, e: 0, pids: ["FeastMeadows", "FeastMeadows_Material"] },
  { id: "c-feast-bosque", name: "Bufé del Bosque Negro", en: "Black Forest buffet platter", h: 35, s: 35, e: 0, pids: ["FeastBlackforest", "FeastBlackforest_Material"] },
  { id: "c-feast-pantano", name: "Delicia del Pantano", en: "Swamp dweller's delight", h: 35, s: 35, e: 0, pids: ["FeastSwamps", "FeastSwamps_Material"] },
  { id: "c-serpiente", name: "Carne de serpiente asada", en: "Cooked serpent meat", h: 70, s: 23, e: 0, pids: ["SerpentMeatCooked"] },
  { ref: "guiso-serpiente" },
  { id: "c-feast-oceano", name: "Botín del marinero", en: "Sailor's bounty", h: 45, s: 45, e: 0, pids: ["FeastOceans", "FeastOceans_Material"] },
  { id: "c-lobo", name: "Carne de lobo asada", en: "Cooked wolf meat", h: 45, s: 15, e: 0, pids: ["CookedWolfMeat"] },
  { id: "c-cecina-lobo", name: "Cecina de lobo", en: "Wolf jerky", h: 33, s: 33, e: 0, pids: ["Wolfjerky"] },
  { ref: "sopa-cebolla" },
  { ref: "brocheta-lobo" },
  { ref: "eyescream" },
  { id: "c-feast-montana", name: "Guiso del leñador de la Montaña", en: "Hearty Mountain logger's stew", h: 45, s: 45, e: 0, pids: ["FeastMountains", "FeastMountains_Material"] },
  { id: "c-huevo", name: "Huevo cocido", en: "Cooked egg", h: 35, s: 12, e: 0, pids: ["CookedEgg"] },
  { id: "c-pollo", name: "Pollo asado", en: "Cooked chicken meat", h: 60, s: 20, e: 0, pids: ["CookedChickenMeat"] },
  { id: "c-lox", name: "Carne de Lox asada", en: "Cooked lox meat", h: 50, s: 16, e: 0, pids: ["CookedLoxMeat"] },
  { ref: "wraps" },
  { ref: "pastel-lox" },
  { ref: "morcilla" },
  { ref: "pan" },
  { id: "c-pan-dulce", name: "Pan dulce glaseado", en: "Frosted sweetbread", h: 43, s: 43, e: 0, pids: ["VikingCupcake"] },
  { id: "c-feast-llanuras", name: "Picnic de las Llanuras", en: "Plains pie picnic", h: 55, s: 55, e: 0, pids: ["FeastPlains", "FeastPlains_Material"] },
  { id: "c-seeker", name: "Carne de Seeker asada", en: "Cooked seeker meat", h: 60, s: 20, e: 0, pids: ["CookedBugMeat"] },
  { id: "c-liebre", name: "Liebre asada", en: "Cooked hare meat", h: 60, s: 20, e: 0, pids: ["CookedHareMeat"] },
  { ref: "bandeja" },
  { ref: "pollo" },
  { ref: "misthare" },
  { ref: "ensalada" },
  { ref: "omelette" },
  { ref: "fishnbread" },
  { ref: "hongo-relleno" },
  { ref: "porridge" },
  { ref: "aspic" },
  { id: "c-feast-mistlands", name: "Festín de hongos de Mistlands", en: "Mushrooms galore á la Mistlands", h: 65, s: 65, e: 33, pids: ["FeastMistlands", "FeastMistlands_Material"] },
  { ref: "cola-asada" },
  { ref: "volture-asado" },
  { ref: "bonemaw-asado" },
  { ref: "svinstew" },
  { ref: "carne-machacada" },
  { ref: "pastel-picante" },
  { ref: "mermelada" },
  { ref: "popurri" },
  { ref: "pastel-corteza" },
  { ref: "caldo-bayas" },
  { ref: "shroomshake" },
  { ref: "verdes" },
  { id: "c-feast-ashlands", name: "Cuenco gourmet de Ashlands", en: "Ashlands gourmet bowl", h: 75, s: 75, e: 38, pids: ["FeastAshlands", "FeastAshlands_Material"] },
];

// Ingredientes de hidromiel que no están en la guía de comidas.
window.MEAD_INGS = {
  "frambuesas": { name: "Frambuesas", en: "Raspberries", pids: ["Raspberry"], where: "Praderas", sources: [{ id: "b-meadows", how: "Arbustos en los bordes de los claros de las Praderas." }] },
  "arandanos": { name: "Arándanos", en: "Blueberries", pids: ["Blueberries"], where: "Bosque Negro", sources: [{ id: "b-blackforest", how: "Arbustos bajos del Bosque Negro." }] },
  "diente-leon": { name: "Diente de león", en: "Dandelion", pids: ["Dandelion"], where: "Praderas", sources: [{ id: "b-meadows", how: "Flor amarilla del suelo de las Praderas." }] },
  "hongo-amarillo": { name: "Hongo amarillo", en: "Yellow mushroom", pids: ["MushroomYellow"], where: "cuevas y criptas", sources: [{ id: "b-blackforest", how: "En cámaras funerarias y cuevas de troll del Bosque Negro, y en las criptas hundidas del Pantano." }] },
  "carbon": { name: "Carbón", en: "Coal", pids: ["Coal"], where: "horno de carbón", sources: [{ id: "horno-carbon", how: "Madera en el horno de carbón. También lo sueltan los surtlings y sale del obliterador." }] },
  "neck-tail": { name: "Cola de neck", en: "Neck tail", pids: ["NeckTail"], where: "Praderas", sources: [{ id: "neck", how: "La sueltan los Neck, las lagartijas de las orillas de las Praderas." }] },
  "toadstool": { name: "Hongo venenoso", en: "Toadstool", pids: ["MushroomBzerker"], where: "Bruja del Pantano", sources: [{ id: "bruja", how: "Se le compra a la Bruja del Pantano por 85 monedas, después de matar a Moder." }] },
  "mero": { name: "Mero", en: "Grouper", pids: ["Fish7", "fish7"], where: "mar de las Llanuras", sources: [{ id: "cana", how: "Se pesca en el agua frente a las Llanuras." }] },
  "ramo": { name: "Ramo fragante", en: "Fragrant bundle", pids: ["FragrantBundle"], where: "Bruja del Pantano", sources: [{ id: "bruja", how: "5 por 140 monedas en la Bruja del Pantano, después de matar a Moder." }] },
  "perca": { name: "Perca", en: "Perch", pids: ["Fish1", "fish1"], where: "Praderas y Bosque Negro", sources: [{ id: "cana", how: "Se pesca en la costa de Praderas y Bosque Negro con carnada común." }] },
  "alga": { name: "Alga fresca", en: "Fresh seaweed", pids: ["FreshSeaweed"], where: "Bruja del Pantano", sources: [{ id: "bruja", how: "5 por 75 monedas en la Bruja del Pantano." }] },
  "tendon": { name: "Tendón de ardilla curado", en: "Cured squirrel hamstring", pids: ["CuredSquirrelHamstring"], where: "Bruja del Pantano", sources: [{ id: "bruja", how: "5 por 80 monedas en la Bruja del Pantano." }] },
  "pez-troll": { name: "Pez troll", en: "Trollfish", pids: ["Fish5", "fish5"], where: "mar del Bosque Negro", sources: [{ id: "cana", how: "Se pesca en el agua frente al Bosque Negro." }] },
  "cascara": { name: "Cáscara de huevo de dragón en polvo", en: "Powdered dragon eggshells", pids: ["PowderedDragonEgg"], where: "Bruja del Pantano", sources: [{ id: "bruja", how: "5 por 120 monedas en la Bruja del Pantano." }] },
  "guijarros": { name: "Guijarros apestosos", en: "Pungent pebbles", pids: ["PungentPebbles"], where: "Bruja del Pantano", sources: [{ id: "bruja", how: "5 por 125 monedas en la Bruja del Pantano." }] },
  "piel-escamas": { name: "Piel de escamas", en: "Scale hide", pids: ["ScaleHide"], where: "Mistlands", sources: [{ id: "liebre", how: "La sueltan las liebres de Mistlands." }] },
  "plumas": { name: "Plumas", en: "Feathers", pids: ["Feathers"], where: "pájaros y árboles", sources: [{ id: "b-meadows", how: "De pájaros, cofres y a veces de árboles talados." }] },
};

// Hidromieles: la base se prepara en el caldero de hidromiel y se fermenta en el fermentador.
window.MEADS = [
  { id: "m-fuego", cat: "fuego", name: "Vino de cebada de resistencia al fuego", en: "Fire resistance barley wine", pid: "BarleyWine", base: "BarleyWineBase", ing: [["cebada", 10], ["moras-nubes", 10]], out: 6, effect: "Resistencia al fuego", dur: 600 },
  { id: "m-frio", cat: "frio", name: "Hidromiel de resistencia al frío", en: "Frost resistance mead", pid: "MeadFrostResist", base: "MeadBaseFrostResist", ing: [["miel", 10], ["cardo", 5], ["bolsa-sangre", 2], ["ojo-greydwarf", 1]], out: 6, effect: "Resistencia a la escarcha", dur: 600 },
  { id: "m-cura-menor", cat: "curacion", name: "Hidromiel de curación menor", en: "Minor healing mead", pid: "MeadHealthMinor", base: "MeadBaseHealthMinor", ing: [["miel", 10], ["arandanos", 5], ["frambuesas", 10], ["diente-leon", 1]], out: 6, effect: "Cura 50 de salud", dur: 10 },
  { id: "m-cura-media", cat: "curacion", name: "Hidromiel de curación media", en: "Medium healing mead", pid: "MeadHealthMedium", base: "MeadBaseHealthMedium", ing: [["miel", 10], ["bolsa-sangre", 4], ["frambuesas", 10], ["diente-leon", 1]], out: 6, effect: "Cura 75 de salud", dur: 10 },
  { id: "m-cura-mayor", cat: "curacion", name: "Hidromiel de curación mayor", en: "Major healing mead", pid: "MeadHealthMajor", base: "MeadBaseHealthMajor", ing: [["miel", 10], ["coagulo", 4], ["jalea", 5]], out: 6, effect: "Cura 125 de salud", dur: 10 },
  { id: "m-cura-larga", cat: "curacion", name: "Hidromiel de curación prolongada", en: "Lingering healing mead", pid: "MeadHealthLingering", base: "MeadBaseHealthLingering", ing: [["savia", 10], ["vinebaya", 10], ["smokepuff", 10]], out: 6, effect: "+25% de regeneración de salud", dur: 300 },
  { id: "m-vigor-menor", cat: "vigor", name: "Hidromiel de vigor menor", en: "Minor stamina mead", pid: "MeadStaminaMinor", base: "MeadBaseStaminaMinor", ing: [["miel", 10], ["frambuesas", 10], ["hongo-amarillo", 10]], out: 6, effect: "Recupera 80 de vigor", dur: 2 },
  { id: "m-vigor-medio", cat: "vigor", name: "Hidromiel de vigor medio", en: "Medium stamina mead", pid: "MeadStaminaMedium", base: "MeadBaseStaminaMedium", ing: [["miel", 10], ["moras-nubes", 10], ["hongo-amarillo", 10]], out: 6, effect: "Recupera 160 de vigor", dur: 2 },
  { id: "m-vigor-largo", cat: "vigor", name: "Hidromiel de vigor prolongado", en: "Lingering stamina mead", pid: "MeadStaminaLingering", base: "MeadBaseStaminaLingering", ing: [["savia", 10], ["moras-nubes", 10], ["jotun", 10]], out: 6, effect: "+25% de regeneración de vigor", dur: 300 },
  { id: "m-mana-menor", cat: "mana", name: "Hidromiel de maná menor", en: "Minor eitr mead", pid: "MeadEitrMinor", base: "MeadBaseEitrMinor", ing: [["miel", 10], ["savia", 5], ["jotun", 2], ["magecap", 5]], out: 6, effect: "Recupera 125 de maná", dur: 10 },
  { id: "m-mana-largo", cat: "mana", name: "Hidromiel de maná prolongado", en: "Lingering eitr mead", pid: "MeadEitrLingering", base: "MeadBaseEitrLingering", ing: [["savia", 10], ["vinebaya", 10], ["magecap", 10]], out: 6, effect: "+25% de regeneración de maná", dur: 300 },
  { id: "m-veneno", cat: "veneno", name: "Hidromiel de resistencia al veneno", en: "Poison resistance mead", pid: "MeadPoisonResist", base: "MeadBasePoisonResist", ing: [["miel", 10], ["cardo", 5], ["neck-tail", 1], ["carbon", 10]], out: 6, effect: "Resistencia al veneno", dur: 600 },
  { id: "m-sabrosa", cat: "vigor", name: "Hidromiel sabrosa", en: "Tasty mead", pid: "MeadTasty", base: "MeadBaseTasty", ing: [["miel", 10], ["frambuesas", 10], ["arandanos", 5]], out: 6, effect: "+100% de regeneración de vigor y −50% de salud", dur: 10 },
  { id: "m-berserkir", cat: "otras", name: "Hidromiel berserkir", en: "Berserkir mead", pid: "MeadBzerker", base: "MeadBaseBzerker", ing: [["hongo", 10], ["hongo-amarillo", 10], ["toadstool", 1]], out: 3, effect: "−80% de vigor al atacar, bloquear y esquivar, pero recibís más daño físico", dur: 20 },
  { id: "m-antipicadura", cat: "otras", name: "Brebaje antipicaduras", en: "Anti-sting concoction", pid: "MeadBugRepellent", base: "MeadBaseBugRepellent", ing: [["moras-nubes", 10], ["mero", 3], ["ramo", 1]], out: 6, effect: "Los mosquitos no te atacan", dur: 600 },
  { id: "m-nadar", cat: "otras", name: "Trago de Vananidir", en: "Draught of Vananidir", pid: "MeadSwimmer", base: "MeadBaseSwimmer", ing: [["diente-leon", 10], ["perca", 2], ["alga", 1]], out: 6, effect: "−50% de vigor al nadar", dur: 300 },
  { id: "m-rapido", cat: "otras", name: "Tónico de Ratatosk", en: "Tonic of Ratatosk", pid: "MeadHasty", base: "MeadBaseHasty", ing: [["miel", 10], ["arandanos", 10], ["tendon", 1]], out: 6, effect: "+15% de velocidad al caminar y correr", dur: 600 },
  { id: "m-troll", cat: "otras", name: "Hidromiel de aguante de troll", en: "Mead of Troll endurance", pid: "MeadStrength", base: "MeadBaseStrength", ing: [["pez-troll", 2], ["miel", 10], ["cascara", 1]], out: 6, effect: "+250 de peso de carga", dur: 300 },
  { id: "m-domar", cat: "otras", name: "Brebaje de susurros animales", en: "Brew of animal whispers", pid: "MeadTamer", base: "MeadBaseTamer", ing: [["cebolla", 5], ["zanahoria", 10], ["guijarros", 1]], out: 6, effect: "Doma el doble de rápido", dur: 600 },
  { id: "m-salto", cat: "otras", name: "Hidromiel de pies ligeros", en: "Lightfoot mead", pid: "MeadLightfoot", base: "MeadBaseLightFoot", ing: [["piel-escamas", 2], ["plumas", 5], ["magecap", 5]], out: 6, effect: "−30% de vigor al saltar y +20% de altura", dur: 600 },
];

// Filtros de hidromiel en el mapa. No respetan los biomas elegidos.
window.MEAD_CATS = [
  { id: "todas",    name: "Todas" },
  { id: "curacion", name: "Curación" },
  { id: "vigor",    name: "Vigor" },
  { id: "mana",     name: "Maná" },
  { id: "veneno",   name: "Veneno" },
  { id: "fuego",    name: "Fuego" },
  { id: "frio",     name: "Frío" },
  { id: "otras",    name: "Otras" },
];

// Estación que pide cada receta (wiki, página del Caldero). El caldero sube un nivel por cada
// mejora pegada: especiero, mesa de carnicero, ollas y sartenes, mortero, rodillos y tablas.
window.STATION_NAMES = {
  caldero: "caldero", horno: "horno de piedra", mesa_prep: "mesa de preparación",
  cocina_hierro: "estación de cocina de hierro", ketill: "caldero de hidromiel", fermentador: "fermentador",
};
window.NEEDS = {
  // caldero con nivel mínimo
  "sopa-cebolla": { caldero: 2 }, "guiso-serpiente": { caldero: 2 },
  "brocheta-lobo": { caldero: 3 }, "eyescream": { caldero: 3 },
  "wraps": { caldero: 4 }, "morcilla": { caldero: 4 },
  "svinstew": { caldero: 5 }, "omelette": { caldero: 5 }, "ensalada": { caldero: 5 }, "aspic": { caldero: 5 },
  "caldo-bayas": { caldero: 5 }, "mermelada": { caldero: 5 }, "porridge": { caldero: 5 },
  "verdes": { caldero: 6 }, "carne-machacada": { caldero: 6 }, "popurri": { caldero: 6 }, "shroomshake": { caldero: 6 },
  // se preparan en la mesa de preparación y se hornean
  "pastel-picante": { mesa_prep: 1, horno: 1 }, "misthare": { mesa_prep: 1, horno: 1 }, "pollo": { mesa_prep: 1, horno: 1 },
  "bandeja": { mesa_prep: 1, horno: 1 }, "pastel-lox": { mesa_prep: 1, horno: 1 }, "pastel-corteza": { mesa_prep: 1, horno: 1 },
  "fishnbread": { mesa_prep: 1, horno: 1 }, "pan": { horno: 1 }, "hongo-relleno": { mesa_prep: 1, horno: 1 },
  // carnes de Ashlands
  "bonemaw-asado": { cocina_hierro: 1 }, "cola-asada": { cocina_hierro: 1 }, "volture-asado": { cocina_hierro: 1 },
};
// todas las hidromieles: base en el caldero de hidromiel y después el fermentador
window.MEAD_NEEDS = { ketill: 1, fermentador: 1 };
